#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored

from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./smile twitterHandle")

    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
 
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    ##get data from twitter using helpers
    tweets = get_user_timeline(sys.argv[1].strip("@"), 50)
    if tweets == None:
        ##if get some text as None then there was an error so print a message and then exit the program
        sys.exit("Invalid twitterHandle")
    
    for tweet in tweets:
        # analyze word
        score = analyzer.analyze(tweet)
        # get color based on score
        color = "green" if score > 0.0 else "red" if score < 0.0 else "yellow"
        ## print score and tweet
        print(colored("{} {}".format(score, tweet), color))


if __name__ == "__main__":
    main()
